package dependencies

object Versions {

    const val multidex = "2.0.1"
    const val gradle = "4.0.1"

    const val buildToolsVersion = "30.0.1"
    const val compileSdk = 30
    const val minSdk = 21
    const val targetSdk = 30

    const val navigation = "2.2.2"

    const val kotlin = "1.3.72"
    const val ktx = "1.3.1"
    const val fragmentKtx = "1.2.5"
    const val ankoVersion = "0.10.8"
    const val butterKnife = "10.0.0"
    const val dagger = "2.27"
    const val daggerHilt = "2.30.1-alpha"
    const val javaX = "1"
    const val daggerHiltExt = "1.0.0-alpha02"
    const val rxJava = "3.0.0"
    const val rxBinding = "2.0.0"
    const val navComponents = "2.3.0-alpha06"
    const val room = "2.3.0-alpha03"
    const val paging = "1.0.1"

    const val browser = "1.2.0"
    const val materialDialogs = "3.2.1"
    const val appcompat = "1.2.0"
    const val legacySupport = "1.0.0"
    const val cardview = "1.0.0"
    const val constraintlayout = "1.1.3"
    const val materialDesign = "1.3.0-alpha02"
    const val swipeRefreshLayout = "1.1.0-alpha03"
    const val flexbox = "1.1.0"
    const val viewpager2 = "1.0.0"
    const val palette = "1.0.0"
    const val recyclerview = "1.1.0"

    const val playCore = "1.7.1"
    const val googleMaps = "17.0.0"
    const val crashlytics = "2.10.1"
    const val playServices = "4.3.4"
    const val playAuth = "18.1.0"
    const val leakCanary = "2.0-alpha-3"

    const val fcm = "21.0.0"
    const val firebaseInAppMessage = "19.1.2"
    const val firebaseVersion = "17.5.1"
    const val firebaseFirestore = "21.4.2"
    const val firebaseAnalytics = "18.0.0"
    const val firebaseCrashlytics = "17.3.0"
    const val firebaseAuth = "19.3.0"

    const val coroutinesVersion = "1.3.7"
    const val coroutinesAndroid = "1.3.5"
    const val coroutinesRetrofit = "0.9.2"
    const val coroutinesPlayServices = "1.3.2"
    const val lifecycleVersion = "2.2.0"
    const val lifecycleKtxVersion = "2.3.0"

    const val glide = "4.11.0"

    const val guava = "27.0.1-android"

    const val gson = "2.8.6"
    const val retrofit2Version = "2.8.1"
    const val retrofit2RxJava = "2.9.0"
    const val okHttp = "4.5.0"

    const val markdownProcessor = "0.1.3"
    const val junitJupiterVersion = "5.6.0"
    const val junitTestAndroidX = "1.1.1"
    const val espressoTest = "3.2.0"
    const val junit4Version = "4.12"
    const val junit5Version = "1.3.2.0"
    const val espressoCore = "3.1.1"
    const val espressoIdlingResource = "3.2.0"
    const val mockkVersion = "1.9.2"
    const val testRunner = "1.2.0"
    const val testCore = "1.2.0"
    const val mockitoKotlinVersion = "2.2.0"
    const val mockitoCoreVersion = "3.3.3"
    const val mockitoInlineVersion = "3.3.3"

    const val fragmentVersion = "1.2.0"
    const val androidxTestExt = "1.1.1"
    const val crashlyticsGradle = "2.4.1"
    const val fabricIo = "1.31.2"

    const val circleImageView1 = "2.2.0"
    const val circleImageView2 = "4.0.1"
    const val timerCountDownView = "2.1.6"
    const val flipTimerView = "v1.5"
    const val indicatorView = "1.0.1@aar"
    const val optView = "1.4.2"
    const val persianDatePicker = "1.2.1"
    const val persianDatePickerDialog = "1.4"
    const val ucrop = "2.2.4"
    const val photoViewZoomable = "2.3.0"
    const val colorPicker1 = "1.1.0"
    const val colorPicker2 = "0.0.15"
    const val fragNav = "3.2.0"
    const val metrix = "0.14.1"
    const val installReferrer = "2.1"
    const val htmlEditor = "1.0.0"
}