name: Android Build Develop Release

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assembleDevelopRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
      - name: Set Name Variables
        run: |
          echo "version=$(git rev-list --count --all)" >> $GITHUB_ENV
          echo "name=DevelopRelease_v." >> $GITHUB_ENV
      - name: Upload APK
        uses: actions/upload-artifact@v2.2.4
        with:
          name: ${{ env.name }}${{ env.version }}
          path: app/build/outputs/apk/develop/release/
          if-no-files-found: error
          retention-days: 1

      - name: Upload file on Slack
        uses: adrey/slack-file-upload-action@1.0.5
        with:
          path: app/build/outputs/apk/develop/release/
          token: ${{ secrets.SLACK_TOKEN }}
          filetype: apk
          channel : ${{ secrets.SLACK_CHANNEL_NAME }}